# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  base_url: "https://app.icedq.net/api/v1"
  workspace_id: "wksc-fde1f71a-6119-53c4-8636-9effcf33dddf"
  token: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5cjVWOVdsaU5jTE12NVFvR1dWSlhUWGpqREgwMXlxUHpKblpxZ2h5WHpnIn0.eyJleHAiOjE3MTg5OTQ1MDEsImlhdCI6MTcxODk4NzMwMSwianRpIjoiMjdhMDZhNGMtYWU5ZC00OTllLThlMTItNzFlOTc2NjdhYTI1IiwiaXNzIjoiaHR0cHM6Ly9hcHAuaWNlZHEubmV0L2F1dGgvcmVhbG1zL2lhbS5pY2VkcSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJkODdjOTY3OC1iODRkLTRjZDUtYTBiOS00ZmZjOTY1ZWEwOWQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJpY2VkcS5hZG1pbi11aSIsInNlc3Npb25fc3RhdGUiOiJiZTc2NTFhZi1kZmE0LTRmNDItYTJkMy0xZGJhNDU5YTE1NjgiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cHM6Ly9hcHAuaWNlZHEubmV0Il0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJ3a3NjLWNkNWMzYjY4LWU2OWEtNWM5Mi1iNTdiLWFlNTU3NDBmYjNjNy5FeGVjdXRvciIsIndrc2MtZTAwZWYxZGEtYjY3Mi01ZGQ2LTg4ODQtNzllNTY4ZDU5YmJlLk93bmVyIiwid2tzYy0wYWNjNGZlYS03Mzg4LTUwMDQtODE4Ni0wNjE4ZGEwMzhjNmMuRXhlY3V0b3IiLCJ3a3NjLTU4YzJlNWJiLTU3OWMtNThkMC05NWIyLTA0YzljOTM4YTZlYi5Pd25lciIsIndrc2MtMjUxOTRmZGUtMDdiMC01YWE4LWExZjAtY2Q1OTI1ODA4ZGZlLk93bmVyIiwid2tzYy0yYzU1YmIwZS03YWZkLTU2MzYtYTU0Zi00NTRmNWEzYWM0NWEuQ29udHJpYnV0b3IiLCJkZWZhdWx0LXJvbGVzLWlhbS5pY2VkcSIsIndrc2MtOTcwMDhjMTktYjViNi01MjIwLWI3M2QtN2JjOWM5MjE5NGM5Lk93bmVyIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIndrc2MtMjEzNjVmY2UtNGM5Yi01N2M1LWE4OWYtN2QxMDIyMzNmMzFkLk93bmVyIiwid2tzYy1hY2E0NDMyZi04MGFhLTUyMzgtODQ0ZS05NmQ1NDliNzIyY2QuT3duZXIiLCJ3a3NjLWZkZTFmNzFhLTYxMTktNTNjNC04NjM2LTllZmZjZjMzZGRkZi5Pd25lciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6ImJlNzY1MWFmLWRmYTQtNGY0Mi1hMmQzLTFkYmE0NTlhMTU2OCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6IkFudWogQ2hhd2RhIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYW51ai5jIiwiZ2l2ZW5fbmFtZSI6IkFudWoiLCJmYW1pbHlfbmFtZSI6IkNoYXdkYSIsImVtYWlsIjoiYW51ai5jQHRvcmFuYWluYy5jb20ifQ.H8va34cHlBphefufASfcr2PaBx5D4wRu1e-8q7pI-8RSFLKWTBpgjugDLu6L9fcw-z-pTBVjWehyev7K1hZiCRS5-nPh24mr7SaG75GKNLMN9bp1Q2KreEt3UD0DEbtfyevBVYXPNi8ZNw3D-sahhTSqlHgxS0fwiLUqUiF0as-YNZy8bkLW_Lg3HbbG3bV_K7Avh7qzMpWo5M4VbUDvkYzx2JmNs9GAoGdVlhHwWbkv941UtrCqG2qZ-HI1-qYxQ6PGhuzFVrvqhW_Of-fZkHBymbXKEvDPtYx4vW9J0bgjWbBpJ7FLMPhmtlA3fXZUlgRb709cyvvZUxW0Paqi2w"
  rule_id: "rule-35a6cd0b-76b3-5dbf-b112-a05b52c9b95d"

steps:
- script: echo Rule Run Demo!
  displayName: 'Start pipeline'

- task: PowerShell@2
  displayName: "Execute Regression"
  inputs:
    filePath: 'pipeline.ps1'
    arguments: '-e $(base_url) -w $(workspace_id) -t $(token) -r $(rule_id)'
    pwsh: true
