# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  base_url: $(base_url)
  workspace_id: $(workspace_id)
  token: $(token)
  rule_id: $(rule_id)

steps:
- script: echo Data Vision 2022 Demo!
  displayName: 'Start pipeline'

- task: PowerShell@2
  displayName: "Execute Regression"
  inputs:
    filePath: 'scripts/execute-regression-v1.ps1'
    arguments: '-e $(base_url) -w $(workspace_id) -t $(token) -r $(rule_id)'
    pwsh: true

